### ISSUE TITLE
random ID could be overflow

### ISSUE THREAD

**Issue by A30225** [VenRaaS/rec-api#1]
https://github.com/VenRaaS/rec-api/blob/master/common/src/main/java/org/venraas/recomd/common/RecomdID.java

**Comment by Eric0329** [comment]
This won't happen.
the integer/long value will round down to MIN_VALUE.
http://stackoverflow.com/questions/8513826/atomicinteger-incrementation

**Comment by Eric0329** [comment]
also apply `recomdSerialNum_.compareAndSet(Long.MAX_VALUE, 0); ` to reset
https://github.com/VenRaaS/rec-api/commit/ff06494cc5fb5c79f5bf4bbf9cd027615e36626e

**Comment by A30225** [comment]
這麼方便!

**Comment by Eric0329** [comment]
哈~如果你verify沒問題
就幫忙close這個 ISSUE吧!
thx
